/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IConfidentialTokenWrappersRegistry {
  export type TokenWrapperPairStruct = {
    tokenAddress: AddressLike;
    confidentialTokenAddress: AddressLike;
    isValid: boolean;
  };

  export type TokenWrapperPairStructOutput = [
    tokenAddress: string,
    confidentialTokenAddress: string,
    isValid: boolean
  ] & {
    tokenAddress: string;
    confidentialTokenAddress: string;
    isValid: boolean;
  };
}

export interface MockRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getConfidentialTokenAddress"
      | "getTokenAddress"
      | "getTokenConfidentialTokenPair"
      | "getTokenConfidentialTokenPairs"
      | "getTokenConfidentialTokenPairsLength"
      | "getTokenConfidentialTokenPairsSlice"
      | "getTokenIndex"
      | "isConfidentialTokenValid"
      | "register"
      | "setValid"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getConfidentialTokenAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfidentialTokenPair",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfidentialTokenPairs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfidentialTokenPairsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfidentialTokenPairsSlice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isConfidentialTokenValid",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setValid",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getConfidentialTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfidentialTokenPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfidentialTokenPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfidentialTokenPairsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfidentialTokenPairsSlice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConfidentialTokenValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setValid", data: BytesLike): Result;
}

export interface MockRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MockRegistry;
  waitForDeployment(): Promise<this>;

  interface: MockRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getConfidentialTokenAddress: TypedContractMethod<
    [token: AddressLike],
    [[boolean, string] & { isValid: boolean; confidentialToken: string }],
    "view"
  >;

  getTokenAddress: TypedContractMethod<
    [wrapper: AddressLike],
    [[boolean, string] & { isValid: boolean; token: string }],
    "view"
  >;

  getTokenConfidentialTokenPair: TypedContractMethod<
    [index: BigNumberish],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput],
    "view"
  >;

  getTokenConfidentialTokenPairs: TypedContractMethod<
    [],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;

  getTokenConfidentialTokenPairsLength: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getTokenConfidentialTokenPairsSlice: TypedContractMethod<
    [from: BigNumberish, to: BigNumberish],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;

  getTokenIndex: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  isConfidentialTokenValid: TypedContractMethod<
    [wrapper: AddressLike],
    [boolean],
    "view"
  >;

  register: TypedContractMethod<
    [token: AddressLike, wrapper: AddressLike],
    [void],
    "nonpayable"
  >;

  setValid: TypedContractMethod<
    [token: AddressLike, valid: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getConfidentialTokenAddress"
  ): TypedContractMethod<
    [token: AddressLike],
    [[boolean, string] & { isValid: boolean; confidentialToken: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenAddress"
  ): TypedContractMethod<
    [wrapper: AddressLike],
    [[boolean, string] & { isValid: boolean; token: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenConfidentialTokenPair"
  ): TypedContractMethod<
    [index: BigNumberish],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenConfidentialTokenPairs"
  ): TypedContractMethod<
    [],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenConfidentialTokenPairsLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenConfidentialTokenPairsSlice"
  ): TypedContractMethod<
    [from: BigNumberish, to: BigNumberish],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenIndex"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isConfidentialTokenValid"
  ): TypedContractMethod<[wrapper: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [token: AddressLike, wrapper: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setValid"
  ): TypedContractMethod<
    [token: AddressLike, valid: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
