/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IConfidentialTokenWrappersRegistry {
  export type TokenWrapperPairStruct = {
    tokenAddress: AddressLike;
    confidentialTokenAddress: AddressLike;
    isValid: boolean;
  };

  export type TokenWrapperPairStructOutput = [
    tokenAddress: string,
    confidentialTokenAddress: string,
    isValid: boolean
  ] & {
    tokenAddress: string;
    confidentialTokenAddress: string;
    isValid: boolean;
  };
}

export interface ShieldVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptAdmin"
      | "addContributor"
      | "admin"
      | "contributorCount"
      | "contributorLabel"
      | "deposit"
      | "getAllRegistryPairs"
      | "getContributors"
      | "getRegistryInfo"
      | "isContributor"
      | "payContributor"
      | "pendingAdmin"
      | "publicBalance"
      | "registry"
      | "removeContributor"
      | "transferAdmin"
      | "unwrapToken"
      | "updateContributorLabel"
      | "withdraw"
      | "wrapToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferCompleted"
      | "AdminTransferInitiated"
      | "ContributorAdded"
      | "ContributorLabelUpdated"
      | "ContributorPaid"
      | "ContributorRemoved"
      | "Deposited"
      | "TokenUnwrapped"
      | "TokenWrapped"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addContributor",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contributorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributorLabel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRegistryPairs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContributors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistryInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isContributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payContributor",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeContributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unwrapToken",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContributorLabel",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapToken",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addContributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllRegistryPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isContributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payContributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeContributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unwrapToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContributorLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wrapToken", data: BytesLike): Result;
}

export namespace AdminTransferCompletedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminTransferInitiatedEvent {
  export type InputTuple = [
    currentAdmin: AddressLike,
    pendingAdmin: AddressLike
  ];
  export type OutputTuple = [currentAdmin: string, pendingAdmin: string];
  export interface OutputObject {
    currentAdmin: string;
    pendingAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributorAddedEvent {
  export type InputTuple = [contributor: AddressLike, label: string];
  export type OutputTuple = [contributor: string, label: string];
  export interface OutputObject {
    contributor: string;
    label: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributorLabelUpdatedEvent {
  export type InputTuple = [contributor: AddressLike, newLabel: string];
  export type OutputTuple = [contributor: string, newLabel: string];
  export interface OutputObject {
    contributor: string;
    newLabel: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributorPaidEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    confidentialToken: AddressLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    confidentialToken: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    confidentialToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributorRemovedEvent {
  export type InputTuple = [contributor: AddressLike];
  export type OutputTuple = [contributor: string];
  export interface OutputObject {
    contributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    token: AddressLike,
    from: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, from: string, amount: bigint];
  export interface OutputObject {
    token: string;
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenUnwrappedEvent {
  export type InputTuple = [wrapper: AddressLike, erc20Token: AddressLike];
  export type OutputTuple = [wrapper: string, erc20Token: string];
  export interface OutputObject {
    wrapper: string;
    erc20Token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWrappedEvent {
  export type InputTuple = [
    erc20Token: AddressLike,
    wrapper: AddressLike,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    erc20Token: string,
    wrapper: string,
    recipient: string
  ];
  export interface OutputObject {
    erc20Token: string;
    wrapper: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShieldVault extends BaseContract {
  connect(runner?: ContractRunner | null): ShieldVault;
  waitForDeployment(): Promise<this>;

  interface: ShieldVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptAdmin: TypedContractMethod<[], [void], "nonpayable">;

  addContributor: TypedContractMethod<
    [contributor: AddressLike, label: string],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  contributorCount: TypedContractMethod<[], [bigint], "view">;

  contributorLabel: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  deposit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllRegistryPairs: TypedContractMethod<
    [],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;

  getContributors: TypedContractMethod<[], [string[]], "view">;

  getRegistryInfo: TypedContractMethod<
    [erc20Token: AddressLike],
    [[boolean, string] & { isValid: boolean; wrapper: string }],
    "view"
  >;

  isContributor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  payContributor: TypedContractMethod<
    [
      contributor: AddressLike,
      confidentialToken: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  pendingAdmin: TypedContractMethod<[], [string], "view">;

  publicBalance: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  removeContributor: TypedContractMethod<
    [contributor: AddressLike],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  unwrapToken: TypedContractMethod<
    [
      confidentialToken: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  updateContributorLabel: TypedContractMethod<
    [contributor: AddressLike, newLabel: string],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  wrapToken: TypedContractMethod<
    [erc20Token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptAdmin"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addContributor"
  ): TypedContractMethod<
    [contributor: AddressLike, label: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "contributorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "contributorLabel"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllRegistryPairs"
  ): TypedContractMethod<
    [],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRegistryInfo"
  ): TypedContractMethod<
    [erc20Token: AddressLike],
    [[boolean, string] & { isValid: boolean; wrapper: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isContributor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "payContributor"
  ): TypedContractMethod<
    [
      contributor: AddressLike,
      confidentialToken: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publicBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeContributor"
  ): TypedContractMethod<[contributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unwrapToken"
  ): TypedContractMethod<
    [
      confidentialToken: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateContributorLabel"
  ): TypedContractMethod<
    [contributor: AddressLike, newLabel: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wrapToken"
  ): TypedContractMethod<
    [erc20Token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminTransferCompleted"
  ): TypedContractEvent<
    AdminTransferCompletedEvent.InputTuple,
    AdminTransferCompletedEvent.OutputTuple,
    AdminTransferCompletedEvent.OutputObject
  >;
  getEvent(
    key: "AdminTransferInitiated"
  ): TypedContractEvent<
    AdminTransferInitiatedEvent.InputTuple,
    AdminTransferInitiatedEvent.OutputTuple,
    AdminTransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "ContributorAdded"
  ): TypedContractEvent<
    ContributorAddedEvent.InputTuple,
    ContributorAddedEvent.OutputTuple,
    ContributorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ContributorLabelUpdated"
  ): TypedContractEvent<
    ContributorLabelUpdatedEvent.InputTuple,
    ContributorLabelUpdatedEvent.OutputTuple,
    ContributorLabelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContributorPaid"
  ): TypedContractEvent<
    ContributorPaidEvent.InputTuple,
    ContributorPaidEvent.OutputTuple,
    ContributorPaidEvent.OutputObject
  >;
  getEvent(
    key: "ContributorRemoved"
  ): TypedContractEvent<
    ContributorRemovedEvent.InputTuple,
    ContributorRemovedEvent.OutputTuple,
    ContributorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "TokenUnwrapped"
  ): TypedContractEvent<
    TokenUnwrappedEvent.InputTuple,
    TokenUnwrappedEvent.OutputTuple,
    TokenUnwrappedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWrapped"
  ): TypedContractEvent<
    TokenWrappedEvent.InputTuple,
    TokenWrappedEvent.OutputTuple,
    TokenWrappedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AdminTransferCompleted(address,address)": TypedContractEvent<
      AdminTransferCompletedEvent.InputTuple,
      AdminTransferCompletedEvent.OutputTuple,
      AdminTransferCompletedEvent.OutputObject
    >;
    AdminTransferCompleted: TypedContractEvent<
      AdminTransferCompletedEvent.InputTuple,
      AdminTransferCompletedEvent.OutputTuple,
      AdminTransferCompletedEvent.OutputObject
    >;

    "AdminTransferInitiated(address,address)": TypedContractEvent<
      AdminTransferInitiatedEvent.InputTuple,
      AdminTransferInitiatedEvent.OutputTuple,
      AdminTransferInitiatedEvent.OutputObject
    >;
    AdminTransferInitiated: TypedContractEvent<
      AdminTransferInitiatedEvent.InputTuple,
      AdminTransferInitiatedEvent.OutputTuple,
      AdminTransferInitiatedEvent.OutputObject
    >;

    "ContributorAdded(address,string)": TypedContractEvent<
      ContributorAddedEvent.InputTuple,
      ContributorAddedEvent.OutputTuple,
      ContributorAddedEvent.OutputObject
    >;
    ContributorAdded: TypedContractEvent<
      ContributorAddedEvent.InputTuple,
      ContributorAddedEvent.OutputTuple,
      ContributorAddedEvent.OutputObject
    >;

    "ContributorLabelUpdated(address,string)": TypedContractEvent<
      ContributorLabelUpdatedEvent.InputTuple,
      ContributorLabelUpdatedEvent.OutputTuple,
      ContributorLabelUpdatedEvent.OutputObject
    >;
    ContributorLabelUpdated: TypedContractEvent<
      ContributorLabelUpdatedEvent.InputTuple,
      ContributorLabelUpdatedEvent.OutputTuple,
      ContributorLabelUpdatedEvent.OutputObject
    >;

    "ContributorPaid(address,address,address)": TypedContractEvent<
      ContributorPaidEvent.InputTuple,
      ContributorPaidEvent.OutputTuple,
      ContributorPaidEvent.OutputObject
    >;
    ContributorPaid: TypedContractEvent<
      ContributorPaidEvent.InputTuple,
      ContributorPaidEvent.OutputTuple,
      ContributorPaidEvent.OutputObject
    >;

    "ContributorRemoved(address)": TypedContractEvent<
      ContributorRemovedEvent.InputTuple,
      ContributorRemovedEvent.OutputTuple,
      ContributorRemovedEvent.OutputObject
    >;
    ContributorRemoved: TypedContractEvent<
      ContributorRemovedEvent.InputTuple,
      ContributorRemovedEvent.OutputTuple,
      ContributorRemovedEvent.OutputObject
    >;

    "Deposited(address,address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "TokenUnwrapped(address,address)": TypedContractEvent<
      TokenUnwrappedEvent.InputTuple,
      TokenUnwrappedEvent.OutputTuple,
      TokenUnwrappedEvent.OutputObject
    >;
    TokenUnwrapped: TypedContractEvent<
      TokenUnwrappedEvent.InputTuple,
      TokenUnwrappedEvent.OutputTuple,
      TokenUnwrappedEvent.OutputObject
    >;

    "TokenWrapped(address,address,address)": TypedContractEvent<
      TokenWrappedEvent.InputTuple,
      TokenWrappedEvent.OutputTuple,
      TokenWrappedEvent.OutputObject
    >;
    TokenWrapped: TypedContractEvent<
      TokenWrappedEvent.InputTuple,
      TokenWrappedEvent.OutputTuple,
      TokenWrappedEvent.OutputObject
    >;

    "Withdrawn(address,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
