/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ShieldVaultFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deployVault"
      | "getAllVaults"
      | "getVaultAt"
      | "getVaultsByAdmin"
      | "isShieldVault"
      | "owner"
      | "registry"
      | "totalVaults"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VaultDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "deployVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultsByAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isShieldVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalVaults",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "deployVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVaultAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultsByAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isShieldVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalVaults",
    data: BytesLike
  ): Result;
}

export namespace VaultDeployedEvent {
  export type InputTuple = [
    vault: AddressLike,
    admin: AddressLike,
    vaultIndex: BigNumberish
  ];
  export type OutputTuple = [vault: string, admin: string, vaultIndex: bigint];
  export interface OutputObject {
    vault: string;
    admin: string;
    vaultIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShieldVaultFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ShieldVaultFactory;
  waitForDeployment(): Promise<this>;

  interface: ShieldVaultFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployVault: TypedContractMethod<
    [admin: AddressLike],
    [string],
    "nonpayable"
  >;

  getAllVaults: TypedContractMethod<[], [string[]], "view">;

  getVaultAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getVaultsByAdmin: TypedContractMethod<
    [admin: AddressLike],
    [string[]],
    "view"
  >;

  isShieldVault: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  totalVaults: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployVault"
  ): TypedContractMethod<[admin: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllVaults"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVaultAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getVaultsByAdmin"
  ): TypedContractMethod<[admin: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isShieldVault"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalVaults"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "VaultDeployed"
  ): TypedContractEvent<
    VaultDeployedEvent.InputTuple,
    VaultDeployedEvent.OutputTuple,
    VaultDeployedEvent.OutputObject
  >;

  filters: {
    "VaultDeployed(address,address,uint256)": TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
    VaultDeployed: TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
  };
}
