/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IConfidentialTokenWrappersRegistry {
  export type TokenWrapperPairStruct = {
    tokenAddress: AddressLike;
    confidentialTokenAddress: AddressLike;
    isValid: boolean;
  };

  export type TokenWrapperPairStructOutput = [
    tokenAddress: string,
    confidentialTokenAddress: string,
    isValid: boolean
  ] & {
    tokenAddress: string;
    confidentialTokenAddress: string;
    isValid: boolean;
  };
}

export interface IConfidentialTokenWrappersRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getConfidentialTokenAddress"
      | "getTokenAddress"
      | "getTokenConfidentialTokenPair"
      | "getTokenConfidentialTokenPairs"
      | "getTokenConfidentialTokenPairsLength"
      | "getTokenConfidentialTokenPairsSlice"
      | "getTokenIndex"
      | "isConfidentialTokenValid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfidentialTokenRegistered"
      | "ConfidentialTokenRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getConfidentialTokenAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfidentialTokenPair",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfidentialTokenPairs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfidentialTokenPairsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenConfidentialTokenPairsSlice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isConfidentialTokenValid",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getConfidentialTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfidentialTokenPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfidentialTokenPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfidentialTokenPairsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenConfidentialTokenPairsSlice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConfidentialTokenValid",
    data: BytesLike
  ): Result;
}

export namespace ConfidentialTokenRegisteredEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    confidentialTokenAddress: AddressLike
  ];
  export type OutputTuple = [
    tokenAddress: string,
    confidentialTokenAddress: string
  ];
  export interface OutputObject {
    tokenAddress: string;
    confidentialTokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfidentialTokenRevokedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    confidentialTokenAddress: AddressLike
  ];
  export type OutputTuple = [
    tokenAddress: string,
    confidentialTokenAddress: string
  ];
  export interface OutputObject {
    tokenAddress: string;
    confidentialTokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IConfidentialTokenWrappersRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IConfidentialTokenWrappersRegistry;
  waitForDeployment(): Promise<this>;

  interface: IConfidentialTokenWrappersRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getConfidentialTokenAddress: TypedContractMethod<
    [erc20TokenAddress: AddressLike],
    [[boolean, string] & { isValid: boolean; confidentialToken: string }],
    "view"
  >;

  getTokenAddress: TypedContractMethod<
    [confidentialWrapperAddress: AddressLike],
    [[boolean, string] & { isValid: boolean; token: string }],
    "view"
  >;

  getTokenConfidentialTokenPair: TypedContractMethod<
    [index: BigNumberish],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput],
    "view"
  >;

  getTokenConfidentialTokenPairs: TypedContractMethod<
    [],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;

  getTokenConfidentialTokenPairsLength: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getTokenConfidentialTokenPairsSlice: TypedContractMethod<
    [fromIndex: BigNumberish, toIndex: BigNumberish],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;

  getTokenIndex: TypedContractMethod<
    [tokenAddress: AddressLike],
    [bigint],
    "view"
  >;

  isConfidentialTokenValid: TypedContractMethod<
    [confidentialWrapperAddress: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getConfidentialTokenAddress"
  ): TypedContractMethod<
    [erc20TokenAddress: AddressLike],
    [[boolean, string] & { isValid: boolean; confidentialToken: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenAddress"
  ): TypedContractMethod<
    [confidentialWrapperAddress: AddressLike],
    [[boolean, string] & { isValid: boolean; token: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenConfidentialTokenPair"
  ): TypedContractMethod<
    [index: BigNumberish],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenConfidentialTokenPairs"
  ): TypedContractMethod<
    [],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenConfidentialTokenPairsLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenConfidentialTokenPairsSlice"
  ): TypedContractMethod<
    [fromIndex: BigNumberish, toIndex: BigNumberish],
    [IConfidentialTokenWrappersRegistry.TokenWrapperPairStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenIndex"
  ): TypedContractMethod<[tokenAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isConfidentialTokenValid"
  ): TypedContractMethod<
    [confidentialWrapperAddress: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ConfidentialTokenRegistered"
  ): TypedContractEvent<
    ConfidentialTokenRegisteredEvent.InputTuple,
    ConfidentialTokenRegisteredEvent.OutputTuple,
    ConfidentialTokenRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ConfidentialTokenRevoked"
  ): TypedContractEvent<
    ConfidentialTokenRevokedEvent.InputTuple,
    ConfidentialTokenRevokedEvent.OutputTuple,
    ConfidentialTokenRevokedEvent.OutputObject
  >;

  filters: {
    "ConfidentialTokenRegistered(address,address)": TypedContractEvent<
      ConfidentialTokenRegisteredEvent.InputTuple,
      ConfidentialTokenRegisteredEvent.OutputTuple,
      ConfidentialTokenRegisteredEvent.OutputObject
    >;
    ConfidentialTokenRegistered: TypedContractEvent<
      ConfidentialTokenRegisteredEvent.InputTuple,
      ConfidentialTokenRegisteredEvent.OutputTuple,
      ConfidentialTokenRegisteredEvent.OutputObject
    >;

    "ConfidentialTokenRevoked(address,address)": TypedContractEvent<
      ConfidentialTokenRevokedEvent.InputTuple,
      ConfidentialTokenRevokedEvent.OutputTuple,
      ConfidentialTokenRevokedEvent.OutputObject
    >;
    ConfidentialTokenRevoked: TypedContractEvent<
      ConfidentialTokenRevokedEvent.InputTuple,
      ConfidentialTokenRevokedEvent.OutputTuple,
      ConfidentialTokenRevokedEvent.OutputObject
    >;
  };
}
