/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConfidentialTokenWrappersRegistry,
  IConfidentialTokenWrappersRegistryInterface,
} from "../../../contracts/interfaces/IConfidentialTokenWrappersRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "confidentialTokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "existingTokenAddress",
        type: "address",
      },
    ],
    name: "ConfidentialTokenAlreadyAssociatedWithToken",
    type: "error",
  },
  {
    inputs: [],
    name: "ConfidentialTokenZeroAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "confidentialTokenAddress",
        type: "address",
      },
    ],
    name: "NoTokenAssociatedWithConfidentialToken",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "confidentialTokenAddress",
        type: "address",
      },
    ],
    name: "NotERC7984",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "confidentialTokenAddress",
        type: "address",
      },
    ],
    name: "RevokedConfidentialToken",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "TokenAddressIsConfidentialTokenAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "existingConfidentialTokenAddress",
        type: "address",
      },
    ],
    name: "TokenAlreadyAssociatedWithConfidentialToken",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "TokenNotRegistered",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenZeroAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "confidentialTokenAddress",
        type: "address",
      },
    ],
    name: "ConfidentialTokenRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "confidentialTokenAddress",
        type: "address",
      },
    ],
    name: "ConfidentialTokenRevoked",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "erc20TokenAddress",
        type: "address",
      },
    ],
    name: "getConfidentialTokenAddress",
    outputs: [
      {
        internalType: "bool",
        name: "isValid",
        type: "bool",
      },
      {
        internalType: "address",
        name: "confidentialToken",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "confidentialWrapperAddress",
        type: "address",
      },
    ],
    name: "getTokenAddress",
    outputs: [
      {
        internalType: "bool",
        name: "isValid",
        type: "bool",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getTokenConfidentialTokenPair",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "confidentialTokenAddress",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType:
          "struct IConfidentialTokenWrappersRegistry.TokenWrapperPair",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenConfidentialTokenPairs",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "confidentialTokenAddress",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType:
          "struct IConfidentialTokenWrappersRegistry.TokenWrapperPair[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenConfidentialTokenPairsLength",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "toIndex",
        type: "uint256",
      },
    ],
    name: "getTokenConfidentialTokenPairsSlice",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "confidentialTokenAddress",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType:
          "struct IConfidentialTokenWrappersRegistry.TokenWrapperPair[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "getTokenIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "confidentialWrapperAddress",
        type: "address",
      },
    ],
    name: "isConfidentialTokenValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IConfidentialTokenWrappersRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IConfidentialTokenWrappersRegistryInterface {
    return new Interface(_abi) as IConfidentialTokenWrappersRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConfidentialTokenWrappersRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IConfidentialTokenWrappersRegistry;
  }
}
